{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "34e1d750-4ff5-4a39-9110-e9b5b3fc09e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2 epsilon_r = 2.20066, lambda_0 = 327642.0306010929 m (12899292.543350115 in)\n",
      "1 h = 0.0018288000000000002 m (0.07200000000000001in) -> min_padding = 0.005486400000000001 and padding = 0.009144000000000001\n",
      "1 Patch electrical length = 110431.53258429868 m (4347698.133240106in)\n",
      "1 Patch width = 0.4511691475302755 m (17.762564863396673in)\n",
      "1 Number of feeds = 3.814697265625e-06, number of levels = -18, Z_patch = 166.21550898321667 ohms.\n",
      "2 Holes: Outer middle holes are centered in patch (not PCB).\n",
      "1 Final dimensions of the antenna are 452.9691475302755 x 110431563.87709868 mm (17.833431005128958 x 4347699.365240105 in)\n",
      "1 There are 0 antennas on this PCB.\n"
     ]
    }
   ],
   "source": [
    "# Preliminary calculations \n",
    "import sys\n",
    "import subprocess\n",
    "from math import sqrt, log, acos, exp, ceil\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# Constants\n",
    "f = 915\n",
    "epsilon_r = 2.20066     # [] Dielectric Constant\n",
    "c         = 299792458   # m/s\n",
    "pi        = 3.14159265358979 # []\n",
    "\n",
    "mu_0       = pi / 2500000              # [] Permeability of free space\n",
    "mu        = mu_0                       # [] Dielectric permeability\t\t\t\n",
    "epsilon   = epsilon_r / (mu_0 * c * c) # [] Dieletric permittivity\n",
    "lambda_0   = c / f                     # [m] Wavelength in free space\n",
    "\n",
    "print(2, \"epsilon_r = \" + str(epsilon_r) + ', lambda_0 = ' + str(lambda_0) + ' m (' + str(lambda_0 / 0.0254) + ' in)')\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# Dimensions\n",
    "\n",
    "airframe_od = 5.5 * 0.0254 # [m] OD of airframe\n",
    "\n",
    "# For more info on these thicknesses, see http://psas.pdx.edu/CpaDesignv3/\n",
    "t_gnd = 0.0050 * 0.0254 # [m] Thickness of GND plane\n",
    "t_radiator = 0.0007 * 0.0254 # [m] Thickness of conductor\n",
    "t_pcb = 0.0050 * 0.0254 # [m] Thickness of the PCB\n",
    "\n",
    "h = (0.005 + 0.062 + 0.005) * 0.0254 # [m] Height of dielectric = 3m super 77 adhesive + UHMW PE + acrylic adhesive\n",
    "min_padding = 3 * h\n",
    "padding = 5 * h\n",
    "print(1,\"h = \" + str(h) + \" m (\" + str(h/0.0254) + \"in) -> min_padding = \" + str(min_padding) + \" and padding = \" + str(padding))\n",
    "\n",
    "d_via = 0.050 * 0.0254 # [m] Diameter of feed via hole (fits Tim's rivet eyelets)\n",
    "\n",
    "l_spacing = 0.36000 # [in] Spacing in diel. Thickness\n",
    "\n",
    "d_countersink = 0.20 * 0.0254   # [m] #4 nylon screw countersnink hole diameter\n",
    "d_screw_hole = 0.089 * 0.0254   # [m] #4-32 FIXME or #4-40?? tap hole\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# Cylindrical Patch\n",
    "\n",
    "# This patch length calculation is from Chapter 7 of The Antenna Engineering Handbook by Richard C. Johnson and Henry Jasik\n",
    "# Also see our notes on http://psas.pdx.edu/AntennaDesignLV2/\n",
    "\n",
    "H = t_gnd + h + t_pcb\n",
    "z_0 = sqrt(mu/epsilon) * log(1 + 2 * h / airframe_od) / (2 * pi)\n",
    "L  = pi *(airframe_od + H) # [m] Note: includes t_pcb, but the copper is on the *inside*. We claim this doesn't make a difference, since we really want to know the length of the FR4.\n",
    "BL = L / (120 * pi * lambda_0) * (-0.540754132818691 - 2 * log(f * h / c))\n",
    "GL = L / (120 * lambda_0)\n",
    "theta = acos((BL * BL + GL * GL-1/(z_0*z_0))/sqrt( ((BL*BL+GL*GL) ** 2)+1/(z_0 ** 4)+2*(BL-GL)*(BL+GL)/(z_0*z_0)))\n",
    "patch_length = (theta * lambda_0) / (2 * pi * sqrt(epsilon_r)) # [m] electrical patch length\n",
    "print(1,\"Patch electrical length = \" + str(patch_length) + \" m (\" + str(patch_length/0.0254) + \"in)\")\n",
    "\n",
    "patch_width = pi * (airframe_od + 2 * t_gnd + 2 * h) # [m] Width of radiator\n",
    "print(1,\"Patch width = \" + str(patch_width) + \" m (\" + str(patch_width/0.0254) + \"in)\")\n",
    "if patch_width > (18 * 0.0254): # 11 x 17 in PCB\n",
    "\tprint('Patch_width of ' + str(patch_width / 0.0254) + ' inches is wider than 18 in maximum')\n",
    "\tsys.exit(1)\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# Calculating feeds and levels. Need at least two feed points.\n",
    "\n",
    "# Calculate the \"fractional\" number of feeds given the width of the patch (which is only dependent on the airframe)\n",
    "feeds  = patch_width / (lambda_0 / sqrt(epsilon_r))\n",
    "\n",
    "# Turn the fractional number of feeds into an integer power of 2, necessary for the corporate feed structure.\n",
    "number_levels = int(ceil(log(feeds, 2)))\n",
    "number_feeds = 2 ** number_levels\n",
    "\n",
    "z_patch = number_feeds * 60 * lambda_0 / patch_width\n",
    "\n",
    "print(1, 'Number of feeds = ' + str(number_feeds) + ', number of levels = ' + str(number_levels) + ', Z_patch = ' + str(z_patch) + ' ohms.')\n",
    "\n",
    "feed_top = 0 # [m] Top of the feed structure (set below)\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# strip_width - this jives within about 1% to http://wcalc.sourceforge.net/cgi-bin/microstrip.cgi\n",
    "\n",
    "def strip_width(impedance):\n",
    "\tB = 377 * pi / (2 * impedance * sqrt(epsilon_r))\n",
    "\tw_h_ratio1 = 2 / pi * (B-1-log(2*B-1)+(epsilon_r-1)/(2*epsilon_r)*(log(B-1)+0.39-0.61/epsilon_r))\t\n",
    "\tA = impedance/60.0*sqrt((epsilon_r+1)/2)+(epsilon_r-1)/(epsilon_r+1)*(0.23+0.11/epsilon_r)\n",
    "\tw_h_ratio2 = 8 * exp(A) / (exp(2 * A ) - 2)\n",
    "\tif w_h_ratio1 > 2 and w_h_ratio2 > 2:\n",
    "\t\tprint(2, \"Microstrip: z = \"+str(impedance)+\" ohms -> width = \"+str(w_h_ratio1*h)+\" m\")\n",
    "\t\treturn w_h_ratio1*h\n",
    "\telse:\n",
    "\t\tprint(2, \"Microstrip: z = \"+str(impedance)+\" ohms -> width = \"+str(w_h_ratio2*h)+\" m\")\n",
    "\t\treturn w_h_ratio2*h\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# Transformer length\n",
    "  \n",
    "def transformer_length(z1,z2):\n",
    "\tz_transformer = sqrt(z1 * z2)\n",
    "\tepsilon_effective = (epsilon_r+1)/2+(epsilon_r-1)/2/sqrt(1+12/(h/strip_width(z_transformer)))\n",
    "\tlambda_effective = lambda_0/sqrt(epsilon_effective)\n",
    "\tprint(2, \"1/4 wave xfmr: z1/z2/z_eff = \" + str(z1) + \"/\" + str(z2) + \"/\" + str(z_transformer) +\"ohms, length = \" + str(lambda_effective/4) + \" m\")\n",
    "\treturn lambda_effective / 4\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# eagle_rect - take coordinates in mm, and write EAGLE script commands to make rectangles in mm\n",
    "\n",
    "def eagle_rect (x1, y1, x2, y2, rotation = 0):\n",
    "\tscript.write('rect r' + str(rotation) + ' (' + str(x1*1000) + ' ' + str(y1*1000) + ') (' + str(x2*1000) + ' ' + str(y2*1000) + ');\\n')\n",
    "\n",
    "def eagle_wire (width, x1, y1, x2, y2):\n",
    "\tscript.write('wire ' + str(width*1000) +' (' + str(x1*1000) + ' ' + str(y1*1000) + ') (' + str(x2*1000) + ' ' + str(y2*1000) + ');\\n')\n",
    "\n",
    "def eagle_hole (d1, x1, y1):\n",
    "\tscript.write('hole ' + str(d1*1000) +' (' + str(x1*1000) + ' ' + str(y1*1000) + ');\\n')\n",
    "\n",
    "def eagle_circle(r1, x1, y1):\n",
    "\tscript.write('circle 0.2 (' + str(x1*1000) + ' ' + str(y1*1000) + ') (' + str(x1*1000) + ' ' + str((y1+r1)*1000) + ');\\n')\n",
    "\n",
    "# ---------------------------------------------------------------------------------------------------------------------\n",
    "# draw_feed\n",
    "\n",
    "def draw_feed(level, feed, y, z_in, z_out, z_next):\n",
    "\n",
    "\tglobal feed_top\n",
    "\n",
    "\t# Calculate this feed's width and the x of the center of the feed\n",
    "\tnumber_feeds = 2 ** level\n",
    "\tfeed_width = patch_width / (2 * (2 ** level))\n",
    "\tx = (-1*number_feeds + feed*2 + 1)*feed_width\n",
    "\tprint(2, \"Feed: Level \" + str(level) + \" feed \" + str(feed) + \"/\" + str(number_feeds)+ \" with y = \" + str(y) + \" and z_in = \" + str(z_in) + \" and z_out = \" + str(z_out))\n",
    "\n",
    "\t# Calculate how many 1/4 wave transformers we need. If Z_in = Z_out/2, then we don't need any. If that's not\n",
    "        # the case, then we need at least one transformer. And if we have room, we'd like two to increase bandwidth.\n",
    "\tif z_in == z_out/2:\n",
    "\t\tnumber_transformers = 0\n",
    "\t\tstrip_length = (feed_width/2 - strip_width(z_out)/2)/2\n",
    "\t\tprint(2,\"Feed: No transformers in this feed.\")\n",
    "\telse:\n",
    "\t\tnumber_transformers = int(feed_width / transformer_length(z_in,z_out)) # This is only approximate\n",
    "\t\tif number_transformers < 1:\n",
    "\t\t\tprint('Feed: Level ' + str(level) + ' has no room for quarter wave transformers.')\n",
    "\t\t\tsys.exit(1)\n",
    "\t\telif number_transformers == 1:\n",
    "\t\t\tprint('Feed: Warning: Level ' + str(level) + ' has only ' + str(number_transformers) + ' quarter wave transformer in it')\n",
    "\t\t\tstrip_length = (feed_width/2 - (transformer_length(z_in, z_out) + strip_width(z_out)/2))/2\n",
    "\t\t\tif strip_length < min_padding:\n",
    "\t\t\t\tprint(\"Feed: Not enough room for even one quarter wave transformer in Level \" + str(level))\n",
    "\t\t\t\tsys.exit(1)\n",
    "\t\telse:\n",
    "\t\t\tnumber_transformers = 2\n",
    "\t\t\tz_intermediate = sqrt((z_in*2) * z_out)\n",
    "\t\t\tstrip_length = (feed_width/2 - (transformer_length(z_in, z_intermediate) + transformer_length(z_intermediate, z_out) + strip_width(z_out)/2))/2\n",
    "\t\t\tif strip_length < min_padding:\n",
    "\t\t\t\tprint('Feed: Warning: level ' + str(level) + 's strip_length of ' + str(strip_length) + ' m is < min_padding.')\n",
    "\t\t\t\tprint('Feed: Warning: moving to one quarter wave transformer in Level ' + str(level))\n",
    "\t\t\t\tnumber_transformers = 1\n",
    "\t\t\t\tstrip_length = (feed_width/2 - (transformer_length(z_in, z_out) + strip_width(z_out)/2))/2\n",
    "\n",
    "\t# Draw microstrip at Zin from center to either the first q wave xfrmr or to the Zout 90 degree strip\n",
    "\tx_offset = strip_length\n",
    "\ty_width = strip_width(z_in*2)/2\n",
    "\teagle_rect(x, y-y_width, x-x_offset, y+y_width)\n",
    "\teagle_rect(x, y-y_width, x+x_offset, y+y_width)\n",
    "\n",
    "\t# Draw any quarter wave transformer(s)\n",
    "\tif number_transformers == 1:\n",
    "\t\t# Just one q wave xfrmr\n",
    "\t\tx_offset2 = transformer_length(z_in*2,z_out)\n",
    "\t\ty_width = strip_width(sqrt(z_in*2*z_out))/2\n",
    "\t\teagle_rect(x-x_offset, y+y_width, x-x_offset-x_offset2, y-y_width)\n",
    "\t\teagle_rect(x+x_offset, y-y_width, x+x_offset+x_offset2, y+y_width)\n",
    "\t\tx_offset += x_offset2\n",
    "\telif number_transformers == 2:\n",
    "\t\t# 1 of 2 q wave xfrmr\n",
    "\t\tx_offset2 = transformer_length(z_in*2, z_intermediate)\n",
    "\t\ty_width = strip_width(sqrt(z_in*2 * z_intermediate))/2\n",
    "\t\teagle_rect(x-x_offset, y+y_width, x-x_offset-x_offset2, y-y_width)\n",
    "\t\teagle_rect(x+x_offset, y-y_width, x+x_offset+x_offset2, y+y_width)\n",
    "\t\tx_offset += x_offset2\n",
    "\t\t# 2 of 2 q wave xfrmr\n",
    "\t\tx_offset2 = transformer_length(z_intermediate,z_out)\n",
    "\t\ty_width = strip_width(sqrt(z_intermediate*z_out))/2\n",
    "\t\teagle_rect(x-x_offset, y+y_width, x-x_offset-x_offset2, y-y_width)\n",
    "\t\teagle_rect(x+x_offset, y-y_width, x+x_offset+x_offset2, y+y_width)\n",
    "\t\tx_offset += x_offset2\n",
    "\t\n",
    "\t# Draw Zout microstrip to 90 degree bend\n",
    "\tx_offset2 = strip_length\n",
    "\ty_width = strip_width(z_out)/2\n",
    "\teagle_rect(x-x_offset, y+y_width, x-x_offset-x_offset2, y-y_width)\n",
    "\teagle_rect(x+x_offset, y-y_width, x+x_offset+x_offset2, y+y_width)\n",
    "\tx_offset += x_offset2\n",
    "\n",
    "\t# If this is the first level, then the Zout microstrip is the most +y thing on the board. Remember it for making holes (see below)\n",
    "\tif level == 0:\n",
    "\t\tfeed_top = y + y_width\n",
    "\t\n",
    "\t# Draw the corner: draw a rectangle and rotate it +/- 45 degrees. Note that the 45 degree mitre is close, but not quite the optimal.\n",
    "\t# We think the optimal is slightly more mitre - see http://en.wikipedia.org/wiki/Microstrip but we're ignoring this because it's hard\n",
    "\t# to do and our v3 CPAs (which worked well) were even fatter since they used wires instead of rotated rectangles. Moose!\n",
    "\n",
    "\thypotemoose = sqrt(2)*strip_width(z_out)\n",
    "\tx_corner =  x-x_offset-strip_width(z_out)/4\n",
    "\ty_corner =  y-y_width+strip_width(z_out)/4\n",
    "\teagle_rect( x_corner-hypotemoose/4, y_corner-hypotemoose/2,  x_corner+hypotemoose/4, y_corner+hypotemoose/2, 315)\n",
    "\teagle_rect(-x_corner-hypotemoose/4, y_corner-hypotemoose/2, -x_corner+hypotemoose/4, y_corner+hypotemoose/2, 45)\n",
    "\n",
    "\t# Zout microstrip at 90 degrees\n",
    "\tx_offset2 = strip_width(z_out)\n",
    "\ty_offset = -y_width\n",
    "\ty_offset2 = -(padding + strip_width(z_next)/2)\n",
    "\teagle_rect(x-x_offset, y+y_offset, x-x_offset-x_offset2, y+y_offset+y_offset2)\n",
    "\teagle_rect(x+x_offset, y+y_offset, x+x_offset+x_offset2, y+y_offset+y_offset2)\n",
    "\n",
    "\treturn y+y_offset+y_offset2\n",
    "\t\n",
    "\n",
    "filename = 'cpa-v4-' + str(f)\n",
    "script = open(filename + '.scr', 'w')\n",
    "d_via = 0.050 * 0.0254 # [m] Diameter of feed via hole (fits Tim's rivet eyelets)\n",
    "\n",
    "with script:\n",
    "\t# -------------------------------------------------------------------------------------------------------------\n",
    "\t# Script setup\n",
    "\n",
    "    script.write('grid mm 1;\\n')\n",
    "    script.write('grid on;\\n')\n",
    "    script.write('layer top;\\n')\n",
    "    script.write('set WIRE_BEND 2;\\n')\n",
    "    script.write('change drill ' + str(d_via*1000) + ';' + '\\n')\n",
    "    script.write('via round (0 0);\\n')\n",
    "\n",
    "\t# -------------------------------------------------------------------------------------------------------------\n",
    "\t# Main loop - do number_levels-1 50/100 ohm levels and 1 Zin/50 levels\n",
    "    y = 0\n",
    "    for level in range(number_levels):\n",
    "        if level == number_levels - 1:\n",
    "            z_in  = z_patch/2\n",
    "            z_out = z_patch\n",
    "            z_next = 200 # There's no \"next\" patch, so make it super thin.\n",
    "        elif level == number_levels - 2:\n",
    "            if number_levels == 2:\n",
    "                z_in = 50\n",
    "                z_out = z_patch/2\n",
    "                z_next = z_patch\n",
    "            else:\n",
    "                z_out = z_patch/4\n",
    "                z_out = z_patch/2\n",
    "                z_next = z_patch\n",
    "        elif level == number_levels - 3:\n",
    "            z_in = 50;\n",
    "            z_out = z_patch/4\n",
    "            z_next = z_patch/4\n",
    "        elif level == number_levels - 4:\n",
    "            z_in = 50\n",
    "            z_out = 50\n",
    "            z_next = z_patch/4\n",
    "        else:\n",
    "            z_in = 50\n",
    "            z_out = 50\n",
    "            z_next = 50\n",
    "        \n",
    "        \n",
    "       \n",
    "    \n",
    "\t\t# # There are 2^level feed structures on each level (level 0 = 1, level 1 = 2, level 2 = 4, etc)\n",
    "\t\t# number_feeds = 2 ** level\n",
    "\t\t# for feed in range(number_feeds):\n",
    "\t\t# \theight = draw_feed(level, feed, y, z_in, z_out, z_next)\n",
    "\t\t# y = height\n",
    "\n",
    "\t\t# There are 2^level feed structures on each level (level 0 = 1, level 1 = 2, level 2 = 4, etc)\n",
    "        number_feeds = 2 ** level\n",
    "        for feed in range(number_feeds):\n",
    "            height = draw_feed(level, feed, y, z_in, z_out, z_next)\n",
    "        y = height\n",
    "\n",
    "\t# Draw the final patch\n",
    "    eagle_rect(-patch_width/2, y, patch_width/2, y-patch_length)\n",
    "    y -= patch_length\n",
    "\n",
    "\t# Holes: Determine if middle level holes at ends of the patch should be centered on PCB or on the patch.\n",
    "    top_row = feed_top + min_padding + d_countersink/2\n",
    "    bottom_row = y - min_padding - d_countersink/2\n",
    "    if ((top_row - bottom_row)/2 + bottom_row) > y + patch_length:\n",
    "        middle_row = (top_row - bottom_row)/2 + bottom_row\n",
    "        print(2,\"Holes: Outer middle holes are centered in PCB (not patch).\")\n",
    "    else:\n",
    "        middle_row = y + patch_length/2\n",
    "        print(2,\"Holes: Outer middle holes are centered in patch (not PCB).\")\n",
    "\n",
    "\t# Precalculate the columns\n",
    "\n",
    "    x_outer_holes = patch_width/2 - 0.100*0.0254 - d_countersink/2\n",
    "    x_innner_holes = patch_width/4\n",
    "\n",
    "\n",
    "\t# #4-40 nylon countersunk hold down screw locations\n",
    "    eagle_hole(d_screw_hole, -x_outer_holes, top_row)\n",
    "    eagle_hole(d_screw_hole, -x_outer_holes, middle_row)\n",
    "    eagle_hole(d_screw_hole, -x_outer_holes, bottom_row)\n",
    "    eagle_hole(d_screw_hole, -x_innner_holes, top_row)\n",
    "    eagle_hole(d_screw_hole, -x_innner_holes, bottom_row)\n",
    "    eagle_hole(d_screw_hole, 0, top_row)\n",
    "    eagle_hole(d_screw_hole, 0, bottom_row)\n",
    "    eagle_hole(d_screw_hole, x_innner_holes, top_row)\n",
    "    eagle_hole(d_screw_hole, x_innner_holes, bottom_row)\n",
    "    eagle_hole(d_screw_hole, x_outer_holes, top_row)\n",
    "    eagle_hole(d_screw_hole, x_outer_holes, middle_row)\n",
    "    eagle_hole(d_screw_hole, x_outer_holes, bottom_row)\n",
    "\n",
    "\n",
    "\t# Draw tplace indicators for airframe module hole and counter sunk screw heads\n",
    "    script.write('layer tplace;\\n')\n",
    "    eagle_circle(0.200 / 2 * 0.0254, -(patch_width/2 - 0.100*0.0254 - d_countersink/2), top_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, -(patch_width/2 - 0.100*0.0254 - d_countersink/2), middle_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, -(patch_width/2 - 0.100*0.0254 - d_countersink/2), bottom_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, -patch_width/4, top_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, -patch_width/4, bottom_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, 0, top_row)\n",
    "    eagle_circle(0.250 / 2 * 0.0254, 0, 0)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, 0, bottom_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, patch_width/4, top_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, patch_width/4, bottom_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, patch_width/2 - 0.100*0.0254 - d_countersink/2, top_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, patch_width/2 - 0.100*0.0254 - d_countersink/2, middle_row)\n",
    "    eagle_circle(0.200 / 2 * 0.0254, patch_width/2 - 0.100*0.0254 - d_countersink/2, bottom_row)\n",
    "\n",
    "\n",
    "\t# Draw cutting guides\n",
    "    script.write('layer top;\\n')\n",
    "    x_cutting_guide = patch_width/2 + 0.001/2\n",
    "    eagle_wire(0.001, x_cutting_guide, feed_top, x_cutting_guide, y + patch_length + min_padding)\n",
    "    eagle_wire(0.001, -x_cutting_guide, feed_top, -x_cutting_guide, y + patch_length + min_padding)\n",
    "\t\n",
    "\t# Make the top and bottom of the antenna PCB are outline_padding away from the top and bottom screws\n",
    "\t# Make the left and right of the antenna PCB the outer edge of the cutting guide, so we don't waste PCB material\n",
    "\t# Padding from screw heads to outer edge should be > 1 and < 3 head diameters (according to Tim), so make it 1.5.\n",
    "    outline_padding = d_countersink*1.5\n",
    "    x_outline = x_cutting_guide + 0.001/2 - 0.0002/2\n",
    "    top_outline = top_row + outline_padding\n",
    "    bottom_outline = bottom_row - outline_padding\n",
    "\t# Draw the top and bottom outlines\n",
    "    eagle_wire(0.0002, -x_outline, top_outline, x_outline, top_outline)\n",
    "    eagle_wire(0.0002, -x_outline, top_outline, -x_outline, bottom_outline)\n",
    "    eagle_wire(0.0002, -x_outline, bottom_outline, x_outline, bottom_outline)\n",
    "    eagle_wire(0.0002,  x_outline, top_outline,  x_outline, bottom_outline)\n",
    "\t\n",
    "    # Calculate final widths and lengths\n",
    "    final_width = x_outline * 2\n",
    "    final_length = top_outline - bottom_outline \n",
    "    print(1,'Final dimensions of the antenna are ' + str(final_width*1000) + ' x ' + str(final_length*1000) + ' mm (' + str(final_width/0.0254) + ' x ' + str(final_length/0.0254) + ' in)')\n",
    "\n",
    "\t# Put everything into positive coordinates. Probably not necessary, but we've always done this so yay for fuzzy bunnies.\n",
    "    script.write('group all;\\n')\n",
    "    script.write('move (> 0 0) (' + str(final_width/2*1000) + ' ' + str(-bottom_outline*1000) + ');\\n')\n",
    "\n",
    "\t# If we can fit multiple antennas in under 11 inches, please do.\n",
    "    script.write('group all;\\n')\n",
    "    script.write('cut (0 0);\\n')\n",
    "    y_copy = 0\n",
    "    print(1,\"There are \" + str(int(11 * 0.0254 / final_length)) + \" antennas on this PCB.\")\n",
    "    for i in range(int(11 * 0.0254 / final_length)-1):\n",
    "        y_copy += final_length\n",
    "        script.write('paste (0 ' + str(y_copy*1000) + ');\\n')\n",
    "\n",
    "\t# we're done here. Fit the hole thing in the windo, and exit\n",
    "    script.write('window fit;\\n')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "05582630-27d6-4465-81ce-0c03683bb9f0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38d1d128-763c-4d6d-a00e-f21b37a19ab5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "86a3a3fa-1dd6-4e33-85f7-5a02f2db51a9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
